# Generated by Django 2.2.2 on 2019-10-29 03:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assign_Exam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('assigned_on', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(null=True, upload_to='image/question/')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('topic_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_exam', models.IntegerField(default=0)),
                ('topic', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User_Attempt',
            fields=[
                ('attempt_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_attempted', models.IntegerField(default=0)),
                ('total_correct', models.IntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('update_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_Attempt_Detail',
            fields=[
                ('attempt_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('choose_answer', models.TextField()),
                ('correct_answer', models.TextField(blank=True)),
                ('is_correct', models.BooleanField(blank=True, default=False, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('update_on', models.DateTimeField(auto_now=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt', to='exam.User_Attempt')),
            ],
        ),
        migrations.RemoveField(
            model_name='user_attemp_detail',
            name='attemp',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='total_exam',
        ),
        migrations.AddField(
            model_name='exam',
            name='is_public',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='exam',
            name='is_random',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='exam',
            name='show_question',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='exam',
            name='update_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exam_choice',
            name='update_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='exam_question',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Exam'),
        ),
        migrations.AlterField(
            model_name='exam_question',
            name='question',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exam_question',
            name='update_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='update_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User_Attemp',
        ),
        migrations.DeleteModel(
            name='User_Attemp_Detail',
        ),
        migrations.AddField(
            model_name='user_attempt_detail',
            name='examm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examm', to='exam.Exam'),
        ),
        migrations.AddField(
            model_name='user_attempt_detail',
            name='q',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q_id', to='exam.Exam_Question'),
        ),
        migrations.AddField(
            model_name='user_attempt',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam', to='exam.Exam'),
        ),
        migrations.AddField(
            model_name='user_attempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topic',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Subject'),
        ),
        migrations.AddField(
            model_name='image',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='exam.Exam_Question'),
        ),
        migrations.AddField(
            model_name='assign_exam',
            name='assign_exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.Exam'),
        ),
        migrations.AddField(
            model_name='assign_exam',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exam',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.Topic'),
        ),
        migrations.AlterUniqueTogether(
            name='assign_exam',
            unique_together={('assign_exam', 'user')},
        ),
    ]
