# Generated by Django 2.2.2 on 2019-10-30 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20191029_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_attempt_detail',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_detail', to='exam.User_Attempt'),
        ),
        migrations.AlterField(
            model_name='user_attempt_detail',
            name='is_correct',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
