# Generated by Django 2.2.2 on 2019-11-01 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_auto_20191030_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='timer',
            field=models.IntegerField(default=0),
        ),
    ]
