# Generated by Django 2.2.2 on 2019-11-05 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_exam_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exam',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
