# Generated by Django 2.2.2 on 2019-11-18 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_auto_20191106_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_attempt',
            name='current_total_question',
            field=models.IntegerField(default=1),
        ),
    ]
