export const SUBJECT_START = 'SUBJECT_START'
export const SUBJECT_SUCCESS = 'SUBJECT_SUCCESS'
export const SUBJECT_FAIL = 'SUBJECT_FAIL'
export const SUBJECTS_GET = 'SUBJECTS_GET'
export const SUBJECT_UPDATE = 'SUBJECT_UPDATE'
export const SUBJECT_CREATE = 'SUBJECT_CREATE'
export const SUBJECT_DELETE = 'SUBJECT_DELETE'

export const TOPIC_START = 'TOPIC_START'
export const TOPIC_SUCCESS = 'TOPIC_SUCCESS'
export const TOPIC_FAIL = 'TOPIC_FAIL'
export const TOPICS_GET = 'TOPICS_GET'
export const TOPIC_UPDATE = 'TOPIC_UPDATE'
export const TOPIC_CREATE = 'TOPIC_CREATE'
export const TOPIC_DELETE = 'TOPIC_DELETE'


export const EXAM_START = 'EXAM_START'
export const EXAM_SUCCESS = 'EXAM_SUCCESS'
export const EXAM_FAIL = 'EXAM_FAIL'
export const EXAMS_GET = 'EXAMS_GET'
export const EXAM_UPDATE = 'EXAM_UPDATE'
export const EXAM_CREATE = 'EXAM_CREATE'
export const EXAM_DELETE = 'EXAM_DELETE'

export const QUESTION_LIST_START = 'QUESTION_LIST_START'
export const QUESTION_LIST_FAIL = 'QUESTION_LIST_FAIL'
export const QUESTION_LIST_SUCCESS = 'QUESTION_LIST_SUCCESS'
export const QUESTION_LIST_GET = 'QUESTION_LIST_GET'

export const QUESTION_START = 'QUESTION_START'
export const QUESTION_FAIL = 'QUESTION_FAIL'
export const QUESTION_SUCCESS = 'QUESTION_SUCCESS'
export const QUESTION_GET = 'QUESTION_GET'
export const QUESTION_CREATE = 'QUESTION_CREATE'
export const QUESTION_UPDATE = 'QUESTION_UPDATE'
export const QUESTION_DELETE = 'QUESTION_DELETE'

export const IMAGE_START = 'IMAGE_START'
export const IMAGES_GET = 'IMAGES_GET'
export const IMAGE_SUCCESS = 'IMAGE_SUCCESS'
export const IMAGE_FAIL = 'IMAGE_FAIL'

export const ATTEMPT_FETCHING = 'ATTEMPT_FETCHING'
export const ATTEMPT_FETCH_SUCCESS = 'ATTEMPT_FETCH_SUCCESS'
export const ATTEMPT_FETCH_ERROR = 'ATTEMPT_FETCH_ERROR'
export const ATTEMPT_CLEAR = 'ATTEMPT_CLEAR'

export const ATTEMPT_DETAIL_CREATING = 'ATTEMPT_DETAIL_CREATING'
export const ATTEMPT_DETAIL_CREATE_SUCCESS = 'ATTEMPT_DETAIL_CREATE_SUCCESS'
export const ATTEMPT_DETAIL_CREATE_ERROR = 'ATTEMPT_DETAIL_CREATE_ERROR'

export const ATTEMPT_START = 'ATTEMPT_START'
export const ATTEMPT_SUCCESS = 'ATTEMPT_SUCCESS'
export const ATTEMPT_FAIL = 'ATTEMPT_FAIL'
export const ATTEMPT_GET = 'ATTEMPT_GET'
export const ATTEMPT_CREATE = 'ATTEMPT_CREATE'

export const MARKING_START = 'MARKING_START'
export const MARKING_SUCCESS = 'MARKING_SUCCESS'
export const MARKING_FAIL = 'MARKING_FAIL'
export const MARKINGS_GET = 'MARKING_GET'
export const MARKING_UPDATE = 'MARKING_UPDATE'

export const QUESTION_FETCHING = 'QUESTION_FETCHING';
export const QUESTION_FETCH_SUCCESS = 'QUESTION_FETCH_SUCCESS';
export const QUESTION_FETCH_ERROR = 'QUESTION_FETCH_ERROR';

export const HISTORY_START = 'HISTORY_START'
export const HISTORY_SUCCESS = 'HISTORY_SUCCESS'
export const HISTORY_FAIL = 'HISTORY_FAIL'
export const HISTORYS_GET = 'HISTORYS_GET'

export const LEADERBOARD_START = 'LEADERBOARD_START'
export const LEADERBOARD_SUCCESS = 'LEADERABOARD_SUCCESS'
export const LEADERBOARD_FAIL = 'LEADERBOARD_FAIL'
export const LEADERBOARD_GET = 'LEADERBOARD_GET'

export const EXAM_HISTORY_START = 'EXAM_HISTORY_START'
export const EXAM_HISTORY_SUCCESS = 'EXAM_HISTORY_SUCCESS'
export const EXAM_HISTORY_FAIL = 'EXAM_HISTORY_FAIL'
export const EXAM_HISTORYS_GET = 'EXAM_HISTORYS_GET'

export const ASSIGN_EXAM_START = 'ASSIGN_EXAM_START'
export const ASSIGN_EXAM_SUCCESS = 'ASSIGN_EXAM_SUCCESS'
export const ASSIGN_EXAM_FAIL = 'ASSIGN_EXAM_FAIL'
export const ASSIGN_EXAM_CREATE = 'ASSIGN_EXAM_CREATE'
export const ASSIGN_EXAM_UPDATE = 'ASSIGN_EXAM_UPDATE'
export const ASSIGN_EXAM_DELETE = 'ASSIGN_EXAM_DELETE'
export const ASSIGN_EXAM_GET = 'ASSIGN_EXAM_GET'


export const ASSIGN_EXAMS_LIST_GET = 'ASSIGN_EXAMS_LIST_GET'
export const ASSIGN_EXAMS_LIST_START = 'ASSIGN_EXAMS_LIST_START'
export const ASSIGN_EXAMS_LIST_FAIL = 'ASSIGN_EXAMS__LIST_FAIL'
export const ASSIGN_EXAMS_LIST_SUCCESS = 'ASSIGN_EXAMS_LIST_SUCCESS'


export const USER_START = 'USER_START'
export const USER_SUCCESS = 'USER_SUCCESS'
export const USER_FAIL = 'USER_FAIL'
export const USERS_GET = 'USERS_GET'
export const USER_UPDATE = 'USER_UPDATE'
export const USER_CREATE = 'USER_CREATE'
export const USER_DELETE = 'USER_DELETE'
export const USER_GET = 'USER_GET'

export const PROFILE_START = 'PROFILE_START'
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS'
export const PROFILE_FAIL = 'PROFILE_FAIL'
export const PROFILE_UPDATE = 'PROFILE_UPDATE'
export const PROFILE_GET = 'PROFILE_GET'

export const SET_STEP = 'SET_STEP'
export const UPDATE_FORM = 'UPDATE_FORM'
export const RESET_FORM = 'RESET_FORM'

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_UPDATE = 'AUTH_UPDATE';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

